server:
  port: 7002

# Eureka配置
eureka:
  instance:
    hostname: loaclhost # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # 如果fetch-registry为false 则表示自己为注册中心
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7003/eureka