version: '3.0'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.4
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - mynet

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - mynet

  consul1:
    image: consul
    container_name: consul1
    restart: always
    command: agent -server -bootstrap-expect=3 -node=consul1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - mynet

  consul2:
    image: consul
    container_name: consul2
    command: agent -server -retry-join=consul1 -node=consul2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    restart: always
    depends_on:
      - consul1
    networks:
      - mynet

  consul3:
    image: consul
    container_name: consul3
    command: agent -server -retry-join=consul1 -node=consul3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    restart: always
    depends_on:
      - consul1
    networks:
      - mynet

  consul4:
    image: consul
    container_name: consul4
    command: agent -retry-join=consul1 -node=consul4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    restart: always
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3
    networks:
      - mynet

  sensor-write:
    image: xiaoyh363/sensor-write
    restart: always
    depends_on:
      - consul4
    networks:
      - mynet

  sensor-read:
    image: xiaoyh363/sensor-read
    restart: always
    depends_on:
      - consul4
    networks:
      - mynet

  nenu-api-gateway:
    image: xiaoyh363/nenu-gateway
    restart: always
    container_name: api-gateway
    ports:
      - 80:80
    depends_on:
      - consul4
    networks:
      - mynet

networks:
  mynet:
    name: mynet

volumes:
  influxdb: