server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/, http://localhost:7003/eureka/
  instance:
    instance-id: zuul-test
    prefer-ip-address: true

info:
  app.name: zuul-test

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    provider-test: /test/**
