server:
  port: 80

spring:
  application:
    name: nenu-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: nenu-user
          uri: lb://nenu-user
          predicates:
            - Path=/nenu-user/**
          filters:
            - StripPrefix=1
        - id: nenu-lab
          uri: lb://nenu-lab
          predicates:
            - Path=/nenu-lab/**
          filters:
            - StripPrefix=1
        - id: sensor-read
          uri: lb://sensor-read
          predicates:
            - Path=/sensor/read/**
          filters:
            - StripPrefix=2
        - id: sensor-real-read
          uri: lb:ws://sensor-real-read
          predicates:
            - Path=/ws/**
  profiles:
    active: dev

---
# 开发环境

spring:
  profiles: dev
  cloud:
    consul:
      enabled: false

---
# 生产环境

spring:
  profiles: prod
  cloud:
    consul:
      host: ${CONSUL_SERVER_ADDRESS}
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: nenu-api-gateway
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
