server:
  port: 8002

# spring
spring:
  application:
    name: provider-test

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/, http://localhost:7003/eureka/
  instance:
    instance-id: service-provider-test-8002

# info
info:
  app.name: service-provider-test-8002
