server:
  port: 8000

spring:
  application:
    name: sensor-write-server
  influx:
    url: http://10.227.89.85:8086
    database: nenu_labs
    batch:
      enable: true
      jitter-duration: 500
  cloud:
    consul:
      host: 10.227.89.85
      port: 8500
      discovery:
        service-name: sensor-write-server