server:
  port: 8100

spring:
  application:
    name: sensor-read-server
  influx:
    url: http://influxdb:8086
    database: nenu_labs
  cloud:
    consul:
      host: 10.227.89.85
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: sensor-read-server
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}