server:
  port: 8100

spring:
  application:
    name: sensor-read-server
  influx:
    url: http://${INFLUXDB_SERVER_ADDRESS}:8086
    database: nenu_labs
  cloud:
    consul:
      host: ${CONSUL_SERVER_ADDRESS}
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: sensor-read-server
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}