server:
  port: 8001

# spring
spring:
  application:
    name: springcloud-provider-test

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: service-provider-test

# info
info:
  app.name: service-provider-test
