# 通用配置
spring:
  influx:
    database: nenu_labs
    batch:
      enable: true
      jitter-duration: 500
  mqtt:
    topic: $share/a/sensor
  profiles:
    active: dev

---
# 开发环境

spring:
  profiles: dev
  mqtt:
    url: tcp://192.168.1.10:1883
  influx:
    url: http://localhost:8086

---
# 生产环境

spring:
  profiles: prod
  mqtt:
    url: tcp://${MQTT_BROKER_ADDRESS}:1883
  influx:
    url: http://${INFLUXDB_SERVER_ADDRESS}:8086