server:
  port: 8761

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: influxdb-route
          uri: lb://influxdb-server
          predicates:
            - Path=/influxdb/**
          filters:
            - StripPrefix=1
        - id: websocket-route
          uri: lb:ws://websocket-server
          predicates:
            - Path=/ws/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
