# 通用配置
server:
  port: 8086

spring:
  application:
    name: sensor-monitor
  profiles:
    active: dev   # 默认使用 dev，生产环境运行时需加上 --spring.profiles.active=prod

---
# 开发环境

spring:
  profiles: dev
  mqtt:
    url: tcp://192.168.1.10:1883
    topic: testtopic

---
# 生产环境

spring:
  profiles: prod
